config/routes.rb
Rails.application.routes.draw do
  #get 'user/index'
  get 'user/show'
  #get 'event/index'
  #get 'event/show'
  #get 'static_pages/index'
  get 'static_pages/secret'
root 'events#index'


  devise_for :users
  get 'events/index'
  #get 'events/new'	
  #get 'events/create'
  resources :events do
  resources :attendances
  end
  #resources :user

  devise_scope :user do
  	get '/users/sign_out'=> 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :event
	belongs_to :participant, class_name: "User"
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :attendances 
	has_many :users , through: :attendances 
    belongs_to :admin, class_name: "User"


	validates :start_date, presence: true 
	validates :duration, presence: true, numericality: {:greater_than_or_equal_to => 0}
	validates :title, presence: true, length: { in: 5..140 }
	validates :description, presence: true, length: { in: 20..1000}
	validates :price, presence: true, length: { in: 1..1000}
	validates :location, presence: true

#start_date must be in the future

	validate :start_date_cannot_be_in_the_past
    def start_date_cannot_be_in_the_past
        if start_date < Date.today
            errors.add(:start_date, "can't be in the past")
        end
    end

#duration must be multiple of 5

    validate :duration_is_multiple_by_five
    def duration_is_multiple_by_five
        if (duration.to_i%5  != 0)
            errors.add(:duration, "put value multiple by 5")
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	after_create :welcome_send

	has_many :attendances
	has_many :events, through: :attendances

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_devise_parameters, if: :devise_controller?
  def configure_devise_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :description, :password, :password_confirmation) }
      #devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name,:description, :is_alive, :email, :password, :password_confirmation)}

  end   
end


 

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
   before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  
    def index
      @event = Event.find(params[:event_id])
    end

	def new
     @event = Event.find(params[:event_id])
    end		 


   def create
   	@attendance= Attendance.new(stripe_customer_id:stripe_customer_id,event: @event,participant: current_user)
    @event = Event.find(params[:event_id])                  
                              
  # Amount in cents
  @amount = event.price

  customer = Stripe::Customer.create({
                                       email: params[:stripeEmail],
                                        source: params[:stripeToken ],
                                       })

  charge = Stripe::Charge.create({
                                      customer: customer.id,
                                       amount: @amount,
                                      description: 'Rails Stripe customer',
                                          currency: 'usd',
                                             })

   rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
   end


   
    puts "#"*60
    puts params
    puts "#"*60

   if @attendance.save
   	
   	 redirect_to events_index_path(@event.id) , notice: "votre participation à l'évenement a été pris en compte"
   else 
   	redirect_to events_index_path(@event.id) , error:"votre participation à l'évenement n'a pas été pris en compte"

   end

   
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
  	@events = Event.all
  end
  def show
   @event = Event.find(params[:id])

  end
  def new
  	@event= Event.new
  end

  def create

    puts "#"*60
    puts params
    puts "#"*60
  	 @event = Event.create(start_date:params[:start_date],
  	 	                     duration:params[:duration],
  	 	                     title:params[:title], 
  	 	                     description:params[:description],
  	 	                     price:params[:price], 
  	 	                     location:params[:location],
  	 	                     admin_id:(current_user.id)
  	 	                   )
   if @event.save
      flash[:success] = " 👌"
        redirect_to "/"
    else
    flash[:failed] = "🤔 Attention!!! le titre/contenu n'est pas validé. 🤓 Veillez réessayer svp!"
        render "new"
    end
  end



end




  	 	                  


  

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def secret
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  	@user = User.all
  end

  def show
  	#@user = current_user
  	if params[:id].to_i == current_user.id
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/attendances/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/attendances/new.html.erb
<%= form_tag "/events/#{@event_id}/attendances(" do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%=@event.price%> €</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%=(@event.price)*100%>"
          data-currency = "eur"
          data-locale="auto"></script>

<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
 <!DOCTYPE html>
 <html>
 <head>
 	<title></title>
 </head>
 <body>
  <style>
  	body {background-color: #ff9999;}
  </style>
<% @events.each do |event|%>

<div class="jumbotron">
  <h1 class="display-4">💫 ⭐️ 🌟 ✨<%=event.title%>! 🌟 ✨</h1>
  <p class="lead", style="text-align:center"> <%=event.start_date%></p>
  <hr class="my-4">
  <p  style="text-align:center"> <%=event.description%></p>
  <p style="text-align:center">Prix: <%=event.price%> €</p>
   <p style="text-align:center">Durée: <%=event.duration%> mn</p>
    <p style="text-align:center">Lieu: <%=event.location%> </p>
     <% if user_signed_in? %>
     <p style="text-align:center"> Réalisateur: <%=event.admin.first_name%> </p>
  
    
    <center><a class="btn btn-primary btn-lg",role="button" <%=link_to "Participer",new_event_attendance_path(event.id) , :data => {method: :create} %> </a> </center>

    <%else%>
     
    <p style="text-align:center"> Pour participer inscrivez-vous <%=link_to "ici",new_user_registration_path%> </p>
    
    <%end%>
    
  </p>
</div>
<%end%>

 
               
 </body>
 </html>
     
                    

app/views/events/new.html.erb
<!DOCTYPE html>
<html>
<head>
      <title></title>
</head>
<body>

       <style>
      body {background-color: #ff9999;}
  </style>

<%= form_tag url_for(action: 'create'), method: "post" do %>

     
      <center><%= label_tag 'start_date' %></center>
      <center><%= date_field 'start_date', @event.start_date %></center>
      <br /> <br />

      <center><%= label_tag 'duration' %></center>
      <center><%= text_field 'duration', @event.duration %></center>
      <br /> <br />


      <center><%= label_tag 'title' %></center>
      <center><%= text_field 'title', @event.title %></center>
      <br /> <br />



      <center><%= label_tag 'description' %></center>
      <center><%= text_area_tag 'description', @event.description %></center>
      <br /> <br />


      <center><%= label_tag 'price' %></center>
      <center><%= text_field 'price', @event.price %></center>
      <br /> <br />

      <center><%= label_tag 'location' %></center>
      <center><%= text_field'location', @event.location %></center>
      <br /> <br />

 <center><%= submit_tag "Create Event" %></center>

    <% end %>

</body>
</html>

app/views/events/show.html.erb
<p style="text-align:center" > Voici les détails concernant l'event:</br>
 
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a style="color:  #004080" , class="navbar-brand" href="<%=events_path%>">Eventbrite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
       <a href= "<%=new_event_path%>" class="btn btn-link">Créer un evenement</a>

      </li>
      
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Profile
          </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="/user/show"> Profile</a>
        <a class="dropdown-item"<%= link_to "Se deconnecter", destroy_user_session_path, :data => {:confirm => "Are you sure to log out?",method: :delete}, class: "nav-link" %> </a>
         
           
         </div>
      </div>

        <% else %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Connexion </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= new_user_registration_path %>">S'inscrire</a>
          <a class="dropdown-item" href="<%=new_user_session_path%>">Se connecter</a>
          <div class="dropdown-divider"></div>
         </div>
        </li>
        </ul>
        <% end%>
  
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    
  <div class="container" style="padding-top: 5rem;">
    
    <p class ="notice"><%notice%></p>
    <p class ="alert"><%alert%></p>
    
    <%= yield %>

    
  </body>
</html>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/show.html.erb
Email: <%= current_user.email%></br>
First_name:<%= current_user.first_name %></br>
Last_name: <%= current_user.last_name %></br>
Description: <%= current_user.description %>